
package lab6p2_danielreyes;


import java.io.IOException;
import java.util.ArrayList;
import java.util.ConcurrentModificationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


/**
 *
 * @author alema
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        AdministrarArchivo admi = admin;
        admi.cargarArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenuartista = new javax.swing.JPopupMenu();
        menuitemeliminaralgo = new javax.swing.JMenuItem();
        menuitemodificaralgo = new javax.swing.JMenuItem();
        popupMenuLikeSong = new javax.swing.JPopupMenu();
        menuitemlikeplaylist = new javax.swing.JMenuItem();
        popupMenu_playlist = new javax.swing.JPopupMenu();
        menuitem_agregar = new javax.swing.JMenuItem();
        menuitem_modificar = new javax.swing.JMenuItem();
        menuitem_eliminar = new javax.swing.JMenuItem();
        frame_signupdecision = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_Artista = new javax.swing.JButton();
        Button_Artista1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Button_Nada = new javax.swing.JButton();
        frame_signupartista = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spinneredad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        textfield_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textfield_username = new javax.swing.JTextField();
        Button_crearartista = new javax.swing.JButton();
        textfield_password = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        frame_signupoyente = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        spinneredad2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        textfield_username1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textfield_password1 = new javax.swing.JTextField();
        Buttoncrear_oyente = new javax.swing.JButton();
        frame_login = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textfield_loginuser = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textfield_loginpassword = new javax.swing.JTextField();
        Buttoningresar = new javax.swing.JButton();
        Buttoningresar1 = new javax.swing.JButton();
        frameprincipalcliente = new javax.swing.JFrame();
        tabbedPaneListar = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        textfield_nombreplaylist = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        frameprincipalcantante = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        Button_crearsingle = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        textfield_cancionnombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textfield_duracion = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        textfield_nombreproyecto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        textfield_anio1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree3 = new javax.swing.JTree();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        framec = new javax.swing.JFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_login = new javax.swing.JButton();
        Button_signup = new javax.swing.JButton();
        Button_salir = new javax.swing.JButton();

        menuitemeliminaralgo.setText("Modificar");
        menuitemeliminaralgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemeliminaralgoActionPerformed(evt);
            }
        });
        popupmenuartista.add(menuitemeliminaralgo);

        menuitemodificaralgo.setText("Eliminar");
        menuitemodificaralgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemodificaralgoActionPerformed(evt);
            }
        });
        popupmenuartista.add(menuitemodificaralgo);

        menuitemlikeplaylist.setText("Agregar Playlist a la Biblioteca");
        menuitemlikeplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemlikeplaylistActionPerformed(evt);
            }
        });
        popupMenuLikeSong.add(menuitemlikeplaylist);

        menuitem_agregar.setText("Agregar Canción");
        menuitem_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_agregarActionPerformed(evt);
            }
        });
        popupMenu_playlist.add(menuitem_agregar);

        menuitem_modificar.setText("Modificar Nombre");
        menuitem_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_modificarActionPerformed(evt);
            }
        });
        popupMenu_playlist.add(menuitem_modificar);

        menuitem_eliminar.setText("Eliminar Playlist");
        menuitem_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_eliminarActionPerformed(evt);
            }
        });
        popupMenu_playlist.add(menuitem_eliminar);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Sign up");

        Button_Artista.setBackground(new java.awt.Color(0, 0, 0));
        Button_Artista.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Button_Artista.setForeground(new java.awt.Color(204, 255, 204));
        Button_Artista.setText("Artista");
        Button_Artista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ArtistaMouseClicked(evt);
            }
        });

        Button_Artista1.setBackground(new java.awt.Color(0, 0, 0));
        Button_Artista1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Button_Artista1.setForeground(new java.awt.Color(204, 255, 204));
        Button_Artista1.setText("Oyente");
        Button_Artista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Artista1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("¿El que desea ser?");

        Button_Nada.setBackground(new java.awt.Color(0, 0, 0));
        Button_Nada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Nada.setForeground(new java.awt.Color(204, 255, 204));
        Button_Nada.setText("Volver");
        Button_Nada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NadaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Button_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(Button_Artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Button_Nada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Button_Nada)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_signupdecisionLayout = new javax.swing.GroupLayout(frame_signupdecision.getContentPane());
        frame_signupdecision.getContentPane().setLayout(frame_signupdecisionLayout);
        frame_signupdecisionLayout.setHorizontalGroup(
            frame_signupdecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_signupdecisionLayout.setVerticalGroup(
            frame_signupdecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("Sign up");

        spinneredad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nombre artístico");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Edad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Password");

        Button_crearartista.setBackground(new java.awt.Color(0, 0, 0));
        Button_crearartista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_crearartista.setForeground(new java.awt.Color(204, 255, 204));
        Button_crearartista.setText("Crear");
        Button_crearartista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_crearartistaMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(Button_crearartista, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textfield_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinneredad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(547, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinneredad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_crearartista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jLabel6)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout frame_signupartistaLayout = new javax.swing.GroupLayout(frame_signupartista.getContentPane());
        frame_signupartista.getContentPane().setLayout(frame_signupartistaLayout);
        frame_signupartistaLayout.setHorizontalGroup(
            frame_signupartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_signupartistaLayout.setVerticalGroup(
            frame_signupartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setText("Sign up");

        spinneredad2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 150, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Username");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Password");

        Buttoncrear_oyente.setBackground(new java.awt.Color(0, 0, 0));
        Buttoncrear_oyente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttoncrear_oyente.setForeground(new java.awt.Color(204, 255, 204));
        Buttoncrear_oyente.setText("Crear");
        Buttoncrear_oyente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttoncrear_oyenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(textfield_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(spinneredad2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Buttoncrear_oyente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(547, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinneredad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textfield_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(Buttoncrear_oyente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jLabel10)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout frame_signupoyenteLayout = new javax.swing.GroupLayout(frame_signupoyente.getContentPane());
        frame_signupoyente.getContentPane().setLayout(frame_signupoyenteLayout);
        frame_signupoyenteLayout.setHorizontalGroup(
            frame_signupoyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_signupoyenteLayout.setVerticalGroup(
            frame_signupoyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel13.setText("Log in");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Username");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Password");

        Buttoningresar.setBackground(new java.awt.Color(0, 0, 0));
        Buttoningresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttoningresar.setForeground(new java.awt.Color(204, 255, 204));
        Buttoningresar.setText("Ingresar");
        Buttoningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtoningresarMouseClicked(evt);
            }
        });

        Buttoningresar1.setBackground(new java.awt.Color(0, 0, 0));
        Buttoningresar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttoningresar1.setForeground(new java.awt.Color(204, 255, 204));
        Buttoningresar1.setText("Volver");
        Buttoningresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buttoningresar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(285, 285, 285))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textfield_loginpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_loginuser, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Buttoningresar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39)
                                .addComponent(Buttoningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_loginuser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_loginpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttoningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttoningresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout frame_loginLayout = new javax.swing.GroupLayout(frame_login.getContentPane());
        frame_login.getContentPane().setLayout(frame_loginLayout);
        frame_loginLayout.setHorizontalGroup(
            frame_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_loginLayout.setVerticalGroup(
            frame_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPaneListar.setBackground(new java.awt.Color(0, 0, 0));
        tabbedPaneListar.setForeground(new java.awt.Color(204, 255, 204));
        tabbedPaneListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbedPaneListarMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Nombre");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        tabbedPaneListar.addTab("Nueva Playlist", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Playlist");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jList1.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(33, 33, 33))
        );

        tabbedPaneListar.addTab("Mis Playlists", jPanel7);

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Playlists de otros Usuarios");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTree2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPaneListar.addTab("Buscar Playlists ", jPanel9);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("¿Seguro que desea cerrar sesión?");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Si");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jButton1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        tabbedPaneListar.addTab("Cerrar Sesión", jPanel8);

        javax.swing.GroupLayout frameprincipalclienteLayout = new javax.swing.GroupLayout(frameprincipalcliente.getContentPane());
        frameprincipalcliente.getContentPane().setLayout(frameprincipalclienteLayout);
        frameprincipalclienteLayout.setHorizontalGroup(
            frameprincipalclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneListar)
        );
        frameprincipalclienteLayout.setVerticalGroup(
            frameprincipalclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneListar)
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        Button_crearsingle.setBackground(new java.awt.Color(0, 0, 0));
        Button_crearsingle.setForeground(new java.awt.Color(204, 255, 204));
        Button_crearsingle.setText("Crear Canción");
        Button_crearsingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_crearsingleMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Titulo de la canción");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Duración de cancion (s)");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_cancionnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(Button_crearsingle, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_cancionnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Button_crearsingle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Canción", jPanel10);

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Nombre");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Año");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(204, 255, 204));
        jButton5.setText("Crear Álbum");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(204, 255, 204));
        jButton6.setText("Crear Single");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Canción");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textfield_nombreproyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfield_anio1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_nombreproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_anio1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Lanzamiento", jPanel13);

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamiento");
        jTree3.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTree3);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Lanzamientos", jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("¿Seguro que desea cerrar sesión?");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Si");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jButton3))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cerrar Sesión", jPanel12);

        javax.swing.GroupLayout frameprincipalcantanteLayout = new javax.swing.GroupLayout(frameprincipalcantante.getContentPane());
        frameprincipalcantante.getContentPane().setLayout(frameprincipalcantanteLayout);
        frameprincipalcantanteLayout.setHorizontalGroup(
            frameprincipalcantanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        frameprincipalcantanteLayout.setVerticalGroup(
            frameprincipalcantanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel14.setBackground(new java.awt.Color(204, 255, 204));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Agregar Canción");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(204, 255, 204));
        jButton7.setText("Terminar Álbum");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout framecLayout = new javax.swing.GroupLayout(framec.getContentPane());
        framec.getContentPane().setLayout(framecLayout);
        framecLayout.setHorizontalGroup(
            framecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framecLayout.setVerticalGroup(
            framecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Spotify");

        Button_login.setBackground(new java.awt.Color(0, 0, 0));
        Button_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_login.setForeground(new java.awt.Color(204, 255, 204));
        Button_login.setText("Log in");
        Button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_loginMouseClicked(evt);
            }
        });

        Button_signup.setBackground(new java.awt.Color(0, 0, 0));
        Button_signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_signup.setForeground(new java.awt.Color(204, 255, 204));
        Button_signup.setText("Sign up");
        Button_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_signupMouseClicked(evt);
            }
        });

        Button_salir.setBackground(new java.awt.Color(238, 113, 113));
        Button_salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_salir.setText("Salir");
        Button_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(Button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(Button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(Button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Button_salirMouseClicked

    private void Button_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_signupMouseClicked
        this.setVisible(false);
        frame_signupdecision.pack();
        frame_signupdecision.setLocationRelativeTo(this);
        frame_signupdecision.setVisible(true);
    }//GEN-LAST:event_Button_signupMouseClicked

    private void Button_NadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NadaMouseClicked
        frame_signupdecision.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Button_NadaMouseClicked

    private void Button_ArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ArtistaMouseClicked
        frame_signupdecision.setVisible(false);
        frame_signupartista.pack();
        frame_signupartista.setLocationRelativeTo(this);
        frame_signupartista.setVisible(true);
    }//GEN-LAST:event_Button_ArtistaMouseClicked

    private void Button_Artista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Artista1MouseClicked
        frame_signupdecision.setVisible(false);
        frame_signupoyente.pack();
        frame_signupoyente.setLocationRelativeTo(this);
        frame_signupoyente.setVisible(true);
    }//GEN-LAST:event_Button_Artista1MouseClicked

    private void Button_crearartistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_crearartistaMouseClicked
        Boolean b= false;
        for (Usuario u : listausuarios) {
            if(u.getUsername().equals(textfield_username.getText())){
                b = true;
                JOptionPane.showMessageDialog(frame_signupartista, "El usuario ya existe");
            }
        }
        if ( b== false ){
            if((Integer)spinneredad.getValue() >= 18){    
                Artista a= new Artista(textfield_nombre.getText(),textfield_username.getText() , textfield_password.getText(), (int) spinneredad.getValue());
                listausuarios.add(a);
                
                
               
                textfield_nombre.setText("");
                textfield_username.setText("");
                textfield_password.setText("");
                spinneredad.setValue(0);
                frame_signupartista.setVisible(false);
                this.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(frame_signupartista, "Debe ser mayor de 18 para poder crear una cuenta");
            }
        }    
        
        
    }//GEN-LAST:event_Button_crearartistaMouseClicked

    private void Buttoncrear_oyenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttoncrear_oyenteMouseClicked
        Boolean b= false;
        for (Usuario u : listausuarios) {
            if(u.getUsername().equals(textfield_username1.getText())){
                b = true;
                JOptionPane.showMessageDialog(frame_signupoyente, "El usuario ya existe");
            }
        }
        if ( b== false ){
            if((Integer)spinneredad2.getValue()>= 12){
                
                    Cliente a = new Cliente(textfield_username1.getText(), textfield_password1.getText(), (Integer)spinneredad2.getValue());
                    listausuarios.add(a);
                    
                    
                    
                    textfield_username1.setText("");
                    textfield_password1.setText("");
                    spinneredad2.setValue(0);
                    frame_signupoyente.setVisible(false);
                    this.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(frame_signupoyente, "Debe ser mayor de 12 para poder crear una cuenta");
            }
        }
        
    }//GEN-LAST:event_Buttoncrear_oyenteMouseClicked

    private void ButtoningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtoningresarMouseClicked
        boolean b = false;
        Usuario actual = new Usuario();
        String user = textfield_loginuser.getText();
        String pass = textfield_loginpassword.getText();
        for (Usuario u : listausuarios) {
            if(u.getUsername().equals(user)){
                if(u.getContra().equals(pass)){
                    b = true;
                    actual = u;
                    usuariologeado = u;
                }
            }
        }
        if(b == true){
            if(actual instanceof Artista){
                textfield_loginuser.setText("");
                textfield_loginpassword.setText("");
                frame_login.setVisible(false);
                frameprincipalcantante.pack();
                frameprincipalcantante.setLocationRelativeTo(this);
                frameprincipalcantante.setVisible(true);
                jTabbedPane1.setSelectedComponent(jPanel11);
                
                DefaultTreeModel modelo = (DefaultTreeModel) jTree3.getModel();
                DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
                root.removeAllChildren();
                modelo.reload();
                for (Lanzamiento p : listalanzamientos) {
                    for (int i = 0; i < ((Artista)usuariologeado).getListaalbumes().size(); i++) {
                        if(((Artista)usuariologeado).getListaalbumes().get(i).equals(p)){
                            DefaultMutableTreeNode nodoplaylist = new DefaultMutableTreeNode(p);
                            root.add(nodoplaylist);
                        }
                    }
                    
                }
                modelo.reload();
                
            }else if (actual instanceof Cliente){
                textfield_loginuser.setText("");
                textfield_loginpassword.setText("");
                frame_login.setVisible(false);
                frameprincipalcliente.pack();
                frameprincipalcliente.setLocationRelativeTo(this);
                frameprincipalcliente.setVisible(true);
                tabbedPaneListar.setSelectedComponent(jPanel7);
                
                //tree
                DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
                root.removeAllChildren();
                modelo.reload();
                
                for (Playlistt p : listaplaylist) {
                    for (int i = 0; i < ((Cliente)usuariologeado).getListaplaylist().size(); i++) {
                        if(((Cliente)usuariologeado).getListaplaylist().get(i).equals(p)){
                            DefaultMutableTreeNode nodoplaylist = new DefaultMutableTreeNode(p);
                            root.add(nodoplaylist);
                        }
                    }
                    
                }
                modelo.reload();
                
                
                
                
                
                
            }
        }else{
            JOptionPane.showMessageDialog(frame_login, "Usuario o contraseña invalido");
        }       
    }//GEN-LAST:event_ButtoningresarMouseClicked

    private void Button_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_loginMouseClicked
        this.setVisible(false);
        frame_login.pack();
        frame_login.setLocationRelativeTo(this);
        frame_login.setVisible(true);
    }//GEN-LAST:event_Button_loginMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTreeModel modelo = (DefaultTreeModel) jTree2.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        root.removeAllChildren();
        modelo.reload();
        indice = 0;
        frameprincipalcliente.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        Playlistt p;
        p = new Playlistt(textfield_nombreplaylist.getText(), usuariologeado.getUsername(), 0);
        listaplaylist.add(p);
        ((Cliente)usuariologeado).getListaplaylist().add(p);
        JOptionPane.showMessageDialog(frameprincipalcliente, "Playlist "+ p.getNombre()+" creada con éxito");
        DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodonombre = new DefaultMutableTreeNode(p);
        root.add(nodonombre);
        modelo.reload();
        
        textfield_nombreplaylist.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        jTree1.setSelectionRow(jTree1.getClosestRowForLocation(evt.getX(), evt.getY()));
        DefaultMutableTreeNode nodoactual = (DefaultMutableTreeNode)jTree1.getSelectionPath().getLastPathComponent();
        nodoselected = nodoactual;
        if(evt.getButton() == 3){
            if(nodoselected.getUserObject() instanceof Playlistt){
                popupMenu_playlist.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void menuitem_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_eliminarActionPerformed
        
        try {
            for (Playlistt p : listaplaylist) {
                if (nodoselected.getUserObject().equals(p)) {
                    listaplaylist.remove(p);
                }
            }
            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            modelo.removeNodeFromParent(nodoselected);
            modelo.reload();
            
        } catch (ConcurrentModificationException e) {
            for (Playlistt p : listaplaylist) {
                if (nodoselected.getUserObject().equals(p)) {
                    listaplaylist.remove(p);
                    ((Cliente)usuariologeado).getListaplaylist().remove(p);
                }
            }
            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            modelo.removeNodeFromParent(nodoselected);
            modelo.reload();
            
        }
        
        
    }//GEN-LAST:event_menuitem_eliminarActionPerformed

    private void Buttoningresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buttoningresar1MouseClicked
        textfield_loginuser.setText("");
        textfield_loginpassword.setText("");
        frame_login.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Buttoningresar1MouseClicked

    private void menuitem_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_modificarActionPerformed
       Playlistt p = (Playlistt) nodoselected.getUserObject();
       String nuevonombre = JOptionPane.showInputDialog(frameprincipalcliente,"Ingrese el nuevo nombre de la playlist");
       p.setNombre(nuevonombre);
       nodoselected.setUserObject(p);
    }//GEN-LAST:event_menuitem_modificarActionPerformed

    private void menuitem_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_agregarActionPerformed
        
    }//GEN-LAST:event_menuitem_agregarActionPerformed

    private void tabbedPaneListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedPaneListarMouseClicked
        if(tabbedPaneListar.getSelectedIndex() == 2){
           DefaultTreeModel modelo = (DefaultTreeModel) jTree2.getModel();
           DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
           for (Playlistt p : listaplaylist) {
               if(!((Cliente)usuariologeado).getListaplaylist().contains(p)){
                   DefaultMutableTreeNode nuevonodo = new DefaultMutableTreeNode(p);
                   raiz.add(nuevonodo);
                   
                   for (int i = 0; i < raiz.getChildCount(); i++) {
                       if(raiz.getChildAt(i) == nuevonodo){
                        indice++;
                       }
                   }
                   if(indice > listaplaylist.size()-((Cliente)usuariologeado).getListaplaylist().size()){
                       raiz.remove(nuevonodo);
                   }
                   
                   
               }
           }
           modelo.reload();
       }
    }//GEN-LAST:event_tabbedPaneListarMouseClicked

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked
        jTree2.setSelectionRow(jTree2.getClosestRowForLocation(evt.getX(), evt.getY()));
        DefaultMutableTreeNode nodoactual = (DefaultMutableTreeNode)jTree2.getSelectionPath().getLastPathComponent();
        nodoselected= nodoactual;
        if(evt.getButton()==3){
            if(nodoactual.getUserObject() instanceof Playlistt){
                popupMenuLikeSong.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTree2MouseClicked

    private void menuitemlikeplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemlikeplaylistActionPerformed
        ((Cliente)usuariologeado).getListaplaylistlike().add((Playlistt) nodoselected.getUserObject());
        for (Usuario u : listausuarios) {
            for (int i = 0; i < ((Cliente)u).getListaplaylist().size(); i++) {
                if(((Cliente)u).getListaplaylist().get(i).equals((Playlistt) nodoselected.getUserObject())){
                    ((Cliente)u).getListaplaylist().get(i).setLikes(((Cliente)u).getListaplaylist().get(i).getLikes()+1);
                }
            }
            
        }
        
        JOptionPane.showMessageDialog(frameprincipalcliente, "Se ha agregado la playlist a la biblioteca");
    }//GEN-LAST:event_menuitemlikeplaylistActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultTreeModel modelo = (DefaultTreeModel) jTree3.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        root.removeAllChildren();
        modelo.reload();
        indice = 0;
        frameprincipalcliente.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void Button_crearsingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_crearsingleMouseClicked
    Cancion c;
    c = new Cancion(textfield_cancionnombre.getText(), textfield_duracion.getText(), textfield_cancionnombre.getText());
    ((Artista)usuariologeado).getListacanciones().add(c);
    textfield_cancionnombre.setText("");
    textfield_duracion.setText("");
    
    }//GEN-LAST:event_Button_crearsingleMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
        int cont = 0;
        Single s;
        s = new Single((Cancion) jComboBox1.getSelectedItem(), textfield_nombreproyecto.getText(), textfield_anio1.getText(), 0);
        listalanzamientos.add(s);
        DefaultTreeModel modelo = (DefaultTreeModel)jTree3.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodonombre = new DefaultMutableTreeNode("Single");
        DefaultMutableTreeNode nodosingle = new DefaultMutableTreeNode(s);
        for (int i = 0; i < root.getChildCount(); i++) {
            if(root.getChildAt(i).toString().equals("Single")){
                cont++;
               
            }
        }
        if (cont >0){
            for (int i = 0; i < root.getChildCount(); i++) {
                if(root.getChildAt(i).toString().equals("Single")){
                    ((DefaultMutableTreeNode)root.getChildAt(i)).add(nodosingle);
                    break;
                }
            }
        }else{
            nodonombre.add(nodosingle);
            root.add(nodonombre);
        }
        modelo.reload();
            
            
        
        textfield_nombreproyecto.setText("");
        textfield_anio1.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
        modelo.removeAllElements();
        if(jTabbedPane1.getSelectedIndex()== 1){
            for (int i = 0; i < ((Artista)usuariologeado).getListacanciones().size(); i++) {
                modelo.addElement(((Artista)usuariologeado).getListacanciones().get(i));
            }
            
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        frameprincipalcantante.setVisible(false);
        framec.pack();
        framec.setLocationRelativeTo(this);
        framec.setVisible(true);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox2.getModel();
        modelo.removeAllElements();
        for (int i = 0; i < ((Artista)usuariologeado).getListacanciones().size(); i++) {
                modelo.addElement(((Artista)usuariologeado).getListacanciones().get(i));
        }
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        temp.getListacanciones().add((Cancion) jComboBox2.getSelectedItem());
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        int cont = 0;
        temp.setTitulo(textfield_nombreproyecto.getText());
        temp.setFecha(textfield_anio1.getText());
        temp.setLikes(0);
        temp.setCantidad(temp.getListacanciones().size());
        listalanzamientos.add(temp);
        
        framec.setVisible(false);
        frameprincipalcantante.pack();
        frameprincipalcantante.setLocationRelativeTo(this);
        frameprincipalcantante.setVisible(true);
        DefaultTreeModel modelo = (DefaultTreeModel)jTree3.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodonombre = new DefaultMutableTreeNode("Album");
        DefaultMutableTreeNode nodoalbum = new DefaultMutableTreeNode(temp.getTitulo());
        
        for (int i = 0; i < root.getChildCount(); i++) {
            if(root.getChildAt(i).toString().equals("Album")){
                cont++;
               
            }
        }
        if (cont >0){
            for (int i = 0; i < root.getChildCount(); i++) {
                if(root.getChildAt(i).toString().equals("Album")){
                    for (int j = 0; j < temp.getListacanciones().size(); j++) {
                        DefaultMutableTreeNode nodocancion = new DefaultMutableTreeNode(temp.getListacanciones().get(j));
                        nodoalbum.add(nodocancion);
                    }
                    ((DefaultMutableTreeNode)root.getChildAt(i)).add(nodoalbum);
                    break;
                }
            }
        }else{
            for (int j = 0; j < temp.getListacanciones().size(); j++) {
                        DefaultMutableTreeNode nodocancion = new DefaultMutableTreeNode(temp.getListacanciones().get(j));
                        nodoalbum.add(nodocancion);
            }
            nodonombre.add(nodoalbum);
            root.add(nodonombre);
        }
        modelo.reload();
            
            
        temp = new Album();
        textfield_nombreproyecto.setText("");
        textfield_anio1.setText("");
        jComboBox1.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jTree3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree3MouseClicked
        jTree3.setSelectionRow(jTree3.getClosestRowForLocation(evt.getX(), evt.getY()));
        DefaultMutableTreeNode nodoactual = (DefaultMutableTreeNode)jTree3.getSelectionPath().getLastPathComponent();
        nodoselected= nodoactual;
        if(evt.getButton()==3){
            if(nodoactual.getUserObject() instanceof Lanzamiento){
                popupmenuartista.show(evt.getComponent(),evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_jTree3MouseClicked

    private void menuitemeliminaralgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemeliminaralgoActionPerformed
        try {
            for (Lanzamiento p : listalanzamientos) {
                if (nodoselected.getUserObject().equals(p)) {
                    listalanzamientos.remove(p);
                }
            }
            DefaultTreeModel modelo = (DefaultTreeModel) jTree3.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            modelo.removeNodeFromParent(nodoselected);
            modelo.reload();
            
        } catch (ConcurrentModificationException e) {
            for (Lanzamiento p : listalanzamientos) {
                if (nodoselected.getUserObject().equals(p)) {
                    listalanzamientos.remove(p);
                    
                    
                }
            }
            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            modelo.removeNodeFromParent(nodoselected);
            modelo.reload();
            
        }
    }//GEN-LAST:event_menuitemeliminaralgoActionPerformed

    private void menuitemodificaralgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemodificaralgoActionPerformed
       Lanzamiento p = (Lanzamiento) nodoselected.getUserObject();
       String nuevonombre = JOptionPane.showInputDialog(frameprincipalcliente,"Ingrese el nuevo nombre ");
       p.setTitulo(nuevonombre);
       nodoselected.setUserObject(p);       
    }//GEN-LAST:event_menuitemodificaralgoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Artista;
    private javax.swing.JButton Button_Artista1;
    private javax.swing.JButton Button_Nada;
    private javax.swing.JButton Button_crearartista;
    private javax.swing.JButton Button_crearsingle;
    private javax.swing.JButton Button_login;
    private javax.swing.JButton Button_salir;
    private javax.swing.JButton Button_signup;
    private javax.swing.JButton Buttoncrear_oyente;
    private javax.swing.JButton Buttoningresar;
    private javax.swing.JButton Buttoningresar1;
    private javax.swing.JFrame frame_login;
    private javax.swing.JFrame frame_signupartista;
    private javax.swing.JFrame frame_signupdecision;
    private javax.swing.JFrame frame_signupoyente;
    private javax.swing.JFrame framec;
    private javax.swing.JFrame frameprincipalcantante;
    private javax.swing.JFrame frameprincipalcliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTree jTree3;
    private javax.swing.JMenuItem menuitem_agregar;
    private javax.swing.JMenuItem menuitem_eliminar;
    private javax.swing.JMenuItem menuitem_modificar;
    private javax.swing.JMenuItem menuitemeliminaralgo;
    private javax.swing.JMenuItem menuitemlikeplaylist;
    private javax.swing.JMenuItem menuitemodificaralgo;
    private javax.swing.JPopupMenu popupMenuLikeSong;
    private javax.swing.JPopupMenu popupMenu_playlist;
    private javax.swing.JPopupMenu popupmenuartista;
    private javax.swing.JSpinner spinneredad;
    private javax.swing.JSpinner spinneredad2;
    private javax.swing.JTabbedPane tabbedPaneListar;
    private javax.swing.JTextField textfield_anio1;
    private javax.swing.JTextField textfield_cancionnombre;
    private javax.swing.JTextField textfield_duracion;
    private javax.swing.JTextField textfield_loginpassword;
    private javax.swing.JTextField textfield_loginuser;
    private javax.swing.JTextField textfield_nombre;
    private javax.swing.JTextField textfield_nombreplaylist;
    private javax.swing.JTextField textfield_nombreproyecto;
    private javax.swing.JTextField textfield_password;
    private javax.swing.JTextField textfield_password1;
    private javax.swing.JTextField textfield_username;
    private javax.swing.JTextField textfield_username1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> listausuarios = new ArrayList();
    ArrayList<Playlistt> listaplaylist= new ArrayList();
    ArrayList<Lanzamiento> listalanzamientos = new ArrayList();
    Usuario usuariologeado;
    DefaultMutableTreeNode nodoselected;
    int indice = 0;
    Album temp= new Album();
    AdministrarArchivo admin = new AdministrarArchivo("/.usuario.txt");
}
